on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  lint:
    name: "Lint"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v3"

      - name: "Use Rust 1.75.0"
        uses: "actions-rs/toolchain@v1"
        with:
          toolchain: "1.75.0"
          profile: "default"
          override: true

      - name: "Use Rust cache"
        uses: "Swatinem/rust-cache@v2"
        with:
          cache-on-failure: true

      - name: "Install prettier 3.0.3"
        run: |
          yarn global add prettier@3.0.3

      - name: "Check prettier format"
        run: |
          prettier --ignore-path .gitignore --check .

      - name: "Check Rust format"
        run: |
          cargo fmt --all -- --check

      - name: "Run Clippy lints"
        run: |
          cargo clippy --all --all-targets
